Update sonar front config (coverage)

diff --git a/.github/workflows/frontendSonarqube.yml b/.github/workflows/frontendSonarqube.yml
--- a/.github/workflows/frontendSonarqube.yml
+++ b/.github/workflows/frontendSonarqube.yml
@@ -23,21 +23,26 @@ jobs:
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
       
-      
-      - name: Install packages 
-        working-directory: ./front
-        run: npm ci
-  
-      - name: Test frontend and coverage
-        working-directory: ./front
-        run: npm run test:ci
-        
       - name: Get Jasmine test coverage report
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
+        uses: actions/download-artifact@v4
         with:
           name: Jasmine Report
           path: ./front/coverage/bobapp
+
+      # - name: Install packages 
+      #   working-directory: ./front
+      #   run: npm ci
+  
+      # - name: Test frontend and coverage
+      #   working-directory: ./front
+      #   run: npm run test:ci
+        
+      # - name: Get Jasmine test coverage report
+      #   uses: actions/upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     name: Jasmine Report
+      #     path: ./front/coverage/bobapp
 
       - name: Analyze frontend
         uses: SonarSource/sonarcloud-github-action@master
